services:
  zipzup:
    image: ghcr.io/szaionz/zipzup:nightly
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - selenium
      - postgresql
    environment:
      POSTGRES_USER: zipzup
      POSTGRES_PASSWORD: zipzup
      POSTGRES_DB: zipzup
      POSTGRES_HOST: postgresql

  redis:
    image: valkey/valkey:8.1.2-alpine3.22
  
  selenium:
    image: selenium/standalone-chromium

  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: zipzup
      POSTGRES_PASSWORD: zipzup
      POSTGRES_DB: zipzup

    volumes:
      - postgres_data:/var/lib/postgresql/data

  guide-downloader:
    image: ghcr.io/szaionz/zipzup:nightly
    entrypoint: ["sh", "-c", "su abc -c 'python3 /app/epg_worker.py' && crond -f"]
    user: root
    environment:
      POSTGRES_USER: zipzup
      POSTGRES_PASSWORD: zipzup
      POSTGRES_DB: zipzup
      POSTGRES_HOST: postgresql

volumes:
  postgres_data: {}