services:
  zipzup:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - json:/json
    depends_on:
      - redis
      - cronie
      - selenium

  cronie:
    build:
      context: .
    entrypoint: ["sh", "-c", "chown -R abc:abc /json && su abc -c 'python3 /app/epg.py' && crond -f"]
    user: root
    volumes:
      - json:/json

  redis:
    image: valkey/valkey:8.1.2-alpine3.22
  
  selenium:
    image: selenium/standalone-chromium
volumes:
  json: {}