services:
  zipzup:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    environment:
      POSTGRES_USER: zipzup
      POSTGRES_PASSWORD: zipzup
      POSTGRES_DB: zipzup
      POSTGRES_HOST: postgresql

  redis:
    image: valkey/valkey:8.1.2-alpine3.22
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 1m
      start_interval: 5s
  
  selenium:
    image: selenium/standalone-chromium
    healthcheck:
      test: 'curl -f http://localhost:4444/wd/hub/status || exit 1'
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 1m
      start_interval: 5s

  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: zipzup
      POSTGRES_PASSWORD: zipzup
      POSTGRES_DB: zipzup
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1


      interval: 5s
      start_interval: 5s
      start_period: 5m

    volumes:
      - postgres_data:/var/lib/postgresql/data

  guide-downloader:
    build:
      context: .
    entrypoint: ["sh", "-c", "su abc -c 'python3 /app/epg_worker.py' && crond -f"]
    user: root
    environment:
      POSTGRES_USER: zipzup
      POSTGRES_PASSWORD: zipzup
      POSTGRES_DB: zipzup
      POSTGRES_HOST: postgresql
    depends_on:
      selenium:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy

    

volumes:
  postgres_data: {}